### ISSUE TITLE
Non-standard case for json properties

### ISSUE THREAD

**Issue by happycollision** [HighDynamics/dnd-app#6]
@HighDynamics, you've got the following in your seed data:

https://github.com/HighDynamics/dnd-app/blob/36c25ac6865ef4108a69d1aad11022e6c811f65a/src/server/characters/Arn_Hachem.js#L73-L370

All (nearly all) of the "skills" property names are PascalCase + snake_case (`Capital_Word_Start_With_Underscores_Separating`). As a matter of convention the vast majority of JSON data is transferred using camelCase (`smallBeginningWithCapsOnWordStarts`). Beyond that there are some snake_case apis, but they are the minority. Then PascalCase or Pascal + snake are super rare.

Is there any reason why we cannot convert to the following idea?

```diff
- Craft_Tailor: {
+ craftTailor: {
+   name: "Craft Tailor",
    ability: "intelligence", 
    ranks: 17, 
    miscModifier: 0, 
    classSkill: true, 
    armorCheck: false,
    display: true, 
  },
```
Or even something more like this, where we just have an array of objects, not a hash/dictionary/whatever you'd like to call named properties:

```diff
- skills: {
+ skills: [
-   Appraise: {
+   {
+     name: "Appraise",
      ability: "intelligence", 
      ranks: 0, 
      miscModifier: 4, 
      classSkill: true, 
      armorCheck: false, 
      display: true, 
    }, 
-   Balance: {
+   {
+     name: "Balance",
      ability: "dexterity", 
      ranks: 0, 
      miscModifier: 0, 
      classSkill: false, 
      armorCheck: true, 
      display: true, 
    }, 
```

Let me know which of these changes works best or if there is some reason we can't/shouldn't change it.

**Comment by happycollision** [comment]
By the way, the main reason I am asking is for the backend I am building. I'd be fighting the framework I am using if we wanted these Snake_Pascal property names.

See [the changes I just made](https://github.com/happycollision/dnd_app_server/commit/cdd6cbd486b6598eb785ef2310881a653cab1b04#diff-c47a1aff9bf95e01794823e9077bbcf6c1b6321beadf2ace8ee9496415766c88) to get an understanding of why I am asking this now.

**Comment by HighDynamics** [comment]
Second option is fine.  Just early code I never got to changing.
